import torch

SEQUENCE_LEGTH = 50
HIDDEN_SIZE = 128
DROPOUT_RATE = 0
NUM_LAYERS = 1
BATCH_SIZE = 64
LEARNING_RATE = 2e-3
LEARNING_RATE_DECAY = 0.95
AFTER_N_EPOCHS = 10
NUM_EPOCHS = 50
MOMENTUM = 0.9

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")